{
	
	//SUGESTAO: Implementar agora a função com TFormula (i.e. x[0]*x[1]) e depois "preencher"...
	// ou avaliar e.g. EvalPar(...)
	
gROOT->Reset();
gStyle->SetOptTitle(0);
TCanvas *c = new TCanvas("c", "Phys Comput canvas", 0, 0, 500, 500);
TF1 *f2 = new TF2("f2","x*y",-5,5,-5,5); 

f2->GetXaxis()->SetTitle("x");
f2->GetYaxis()->SetTitle("y");
f2->GetZaxis()->SetTitle("z");

c->SetTheta(26); //angle with hor.plane (usual IDL like 30)
c->SetPhi(11); //rotation around z-axis, 0="facing XZ plane", parallel to +y

/* Originally F.Barao has the gPad global variable (points to current canvas)
   but i deduced that since Canvas is a son of Pad...then Canvas should
	 inherit these function members SetTheta,Phi...so i just used the "c" object
	 instead. If we look to the .C generated by saving the plot drawn (no -q when
	 running the script), we easily confirm that the "developers" do likewise.
gPad->SetTheta(26); //angle with hor.plane (usual IDL like 30)
gPad->SetPhi(11); //rotation around z-axis, 0="facing XZ plane", parallel to +y
gPad->SetLogz();
*/

f2->Draw("surf1");

c->Modified();
c->SaveAs("2Dfunction_surfplot.eps");
}
